version: "3.9"
name: taxi-only-etl

volumes:
  taxi_data:
  event_data:

services:
  extract-taxi:
    image: python:3.11
    volumes:
      - ./download_taxi.py:/data/download_taxi.py
      - taxi_data:/data/output
    working_dir: /data
    command: ["bash", "-c", "python download_taxi.py"]

  process-taxi:
    build: .
    volumes:
      - ./process_taxi.py:/data/process_taxi.py
      - taxi_data:/data/output
    working_dir: /data
    command: ["bash", "-c", "python process_taxi.py"]

  load-data:
    image: rclone/rclone:latest
    volumes:
      - taxi_data:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi

        echo "Cleaning up existing contents of container..."
        rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true

        echo "Copying data to object store..."
        rclone copy /data chi_tacc:$RCLONE_CONTAINER \
          --progress \
          --transfers=32 \
          --checkers=16 \
          --multi-thread-streams=4 \
          --fast-list

        echo "Listing directories in container after load stage:"
        rclone lsd chi_tacc:$RCLONE_CONTAINER

  download-events-monthly:
    build: .
    volumes:
      - ./download_events.py:/data/download_events.py
      - event_data:/data/events
    working_dir: /data
    command: ["bash", "-c", "python download_events.py"]

  process-events-monthly:
    build: .
    volumes:
      - ./process_events.py:/data/process_events.py
      - event_data:/data/events
    working_dir: /data
    command: ["bash", "-c", "python process_events.py"]

  load-events:
    image: rclone/rclone:latest
    volumes:
      - event_data:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi

        echo "Uploading processed_events_2024.csv to chi_tacc:$RCLONE_CONTAINER ..."
        rclone copy /data/processed_events_2024.csv chi_tacc:$RCLONE_CONTAINER \
          --progress \
          --transfers=8 \
          --checkers=8 \
          --multi-thread-streams=4 \
          --fast-list

        echo "Upload complete. Listing files in container:"
        rclone ls chi_tacc:$RCLONE_CONTAINER
  
  extract-taxi-test:
    image: python:3.11
    volumes:
      - ./download_taxi_test.py:/data/download_taxi_test.py
      - taxi_data:/data/output
    working_dir: /data
    command: ["bash", "-c", "python download_taxi_test.py"]

  download-events-test:
    build: .
    volumes:
      - ./download_events_test.py:/data/download_events_test.py
      - event_data:/data/events
    working_dir: /data
    command: ["bash", "-c", "python download_events_test.py"]

  split-datasets:
    build: .
    volumes:
      - ./split_datasets.py:/data/split_datasets.py
      - taxi_data:/data/output
    working_dir: /data
    command: ["bash", "-c", "python split_datasets.py"]
