version: '3.9'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    container_name: airflow_web
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - taxi_data:/mnt/data
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname admin --lastname admin --role Admin --password admin --email admin@example.com && airflow webserver"
    restart: always

  airflow_scheduler:
    image: apache/airflow:2.8.1-python3.11
    container_name: airflow_scheduler
    depends_on:
      - airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - taxi_data:/mnt/data
    command: airflow scheduler
    restart: always

volumes:
  taxi_data:
