version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mlflow_postgres
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflowdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.2
    container_name: mlflow_server
    restart: always
    depends_on:
      - postgres
    environment:
      MLFLOW_TRACKING_URI: http://129.114.25.171:8000
    volumes:
      - ./mlruns:/mlruns  
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "pip install psycopg2-binary &&
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflowdb
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 8000"
      
  ray-head:
    image: rayproject/ray:2.42.1
    container_name: ray-head
    command: |
      /bin/sh -c "
      pip install ray &&
      mkdir -p /tmp/ray && 
      chown -R root:root /tmp/ray &&
      ray metrics launch-prometheus &&
      ray start --head --port=6379 --dashboard-host=0.0.0.0 --block --metrics-export-port=8080"
    ports:
      - "6379:6379" 
      - "8265:8265" 
      - "8080:8080" 
      - "8090:8090" 
      - "9090:9090" 
    shm_size: '12g'
    volumes:
      - ray_tmp:/tmp/ray
    environment:
      - RAY_GRAFANA_HOST=http://grafana:3000
      - RAY_GRAFANA_IFRAME_HOST=http://${HOST_IP}:3000
      - RAY_PROMETHEUS_HOST=http://ray-head:9090
      - RAY_PROMETHEUS_NAME=Prometheus
    user: root
    
  ray-worker-0:
    image: rayproject/ray:2.42.1
    container_name: ray-worker-0
    command: ["ray", "start", "--address=ray-head:6379", "--num-cpus=32", "--block"]
    shm_size: '12g'
    volumes:
      - ray_tmp:/tmp/ray
    depends_on:
      - ray-head

  ray-worker-1:
    image: rayproject/ray:2.42.1
    container_name: ray-worker-1
    command: ["ray", "start", "--address=ray-head:6379", "--num-cpus=32", "--block"]
    shm_size: '12g'
    volumes:
      - ray_tmp:/tmp/ray
    depends_on:
      - ray-head

volumes:
  postgres_data:
  ray_tmp:
