name: train
services:
  jupyter:
    image: quay.io/jupyter/scipy-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /home/cc/MLOPs-Project/train/workspace:/home/jovyan/work # mount workspace
    environment:
      - RAY_HEAD_ADDR=ray-head:6379  # Ensure Ray workers can find the head node
    command: >
      bash -c "pip install ray mlflow && start-notebook.sh"  # Install Ray and then start Jupyter notebook
    depends_on:
      - ray-head  # Make sure ray-head starts before jupyter
    #command: >
    #  bash -c "python3 -m pip install numpy mlflow && start-notebook.sh"
