version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mlflow_postgres
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflowdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.2
    container_name: mlflow_server
    restart: always
    depends_on:
      - postgres
    environment:
      MLFLOW_TRACKING_URI: http://129.114.25.171:8000
    volumes:
      - ./mlruns:/mlruns  
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "pip install psycopg2-binary &&
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflowdb
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 8000"

volumes:
  postgres_data:
